name: "Build"
on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        images:
          - name: server
            workingPath: ./server
          - name: console
            workingPath: ./console
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: silvenga-docker/build-image@latest
      with:
        workingPath: ${{ matrix.images.workingPath }}
        dockerUserName: silvenga-docker
        dockerPassword: ${{ secrets.GITHUB_TOKEN }}
        dockerImageName: ${{ github.repository }}/${{ matrix.images.name }}
        dockerTags: latest,${{ github.sha }}
